- id: commitizen
  name: commitizen check
  description: >
    Check whether the current commit message follows commiting rules. Allow
    empty commit messages by default, because they typically indicate to Git
    that the commit should be aborted.
  entry: cz check
  args: [--allow-abort, --commit-msg-file]
  stages: [commit-msg]
  language: python
  language_version: python3
- id: lint
  name: lint
  entry: make
  args: ["lint"]
  pass_filenames: false
  language: python
  stages: [pre-commit]
- id: format_mdj
  name: format_mdj
  entry: make
  args: ["format_mdj"]
  pass_filenames: false
  language: python
  stages: [pre-commit]
- id: check_commit_msg
  name: check commit message
  description: checks commit message for issue number and typos.
  entry: check_commit_msg
  language: python
  stages: [commit-msg]
- id: eslint
  name: run eslint
  description: run eslint on staged files.
  entry: node_modules/.bin/eslint
  language: system
  stages: [pre-commit]
  types_or: [javascript, jsx, ts, tsx, markdown, mdx]
  args: [--cache]
- id: stylelint
  name: run stylelint
  description: run stylelint on staged files.
  entry: node_modules/.bin/stylelint
  language: system
  stages: [pre-commit]
  types_or: [css, tsx, scss]
  args: [--cache]
- id: check_uv_toml
  name: lint pyproject.toml
  description: checks pyproject.toml files for parseable syntax path dependency.
  entry: check_uv_toml
  language: python
  types: [toml]
  files: pyproject.toml
  stages: [pre-commit]
- id: check_branch_name
  name: check branch name
  description: checks if the current git branch name follows the naming convention.
  entry: check_branch_name
  language: python
  stages: [pre-commit]
